# Workflow for building and deploying a Hugo site to an FTP Site
name: Deploy Hugo site to Netcup Webspace

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify

      - name: Sync files to Netcup
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}
          local-dir: ./public/
          server-dir: ./schmalededomingo.de/httpdocs/
          protocol: ftps
          port: 21
