# Workflow for building and deploying a Hugo site to an FTP Site
name: Deploy Hugo site to Netcup Webspace

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install theme dependencies
        run: |
          npm install
        working-directory: themes/toha

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify

      - name: Sync files to Netcup
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}
          local-dir: ./public/
          remote-dir: /schmalededomingo.de/httpdocs/
          protocol: ftps
          port: 21
